In [1]:
import pandas as pd
df = pd.read_csv('~/notes/CS-py/CS107/files/gpa.csv')
df

,Year,Term,YearTerm,Subject,Number,Course Title,Sched Type,A+,A,A-,...,C+,C,C-,D+,D,D-,F,W,Students,Primary Instructor
0,2025,Spring,2025-sp,AAS,100,Intro Asian American Studies,LCD,3,21,1,...,0,1,0,0,0,0,1,0,28,"Geng, Zhe"
1,2025,Spring,2025-sp,AAS,200,U.S. Race and Empire,LCD,0,33,0,...,0,0,0,0,0,0,1,0,34,"Sawada, Emilia R"
2,2025,Spring,2025-sp,AAS,211,Asian Americans and the Arts,LCD,0,22,1,...,0,0,0,0,0,0,0,0,24,"Sawada, Emilia R"
3,2025,Spring,2025-sp,AAS,215,US Citizenship Comparatively,LCD,5,12,5,...,0,0,0,0,1,0,0,0,30,"Siglos, David G"
4,2025,Spring,2025-sp,AAS,287,Food and Asian Americans,LCD,9,12,8,...,0,0,1,0,0,0,0,1,31,"Kang, Simrat A"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76986,2010,Summer,2010-su,STAT,410,Statistics and Probability II,LEC,5,10,2,...,0,1,3,0,0,0,2,1,31,"Stepanov, Alexei G"
76987,2010,Summer,2010-su,STAT,440,Statistical Data Management,LEC,4,12,8,...,0,0,0,0,0,0,0,0,28,"Unger, David"
76988,2010,Summer,2010-su,TAM,212,Introductory Dynamics,LEC,0,1,3,...,5,1,1,0,2,0,1,0,28,"Morgan, William T"
76989,2010,Summer,2010-su,TAM,251,Introductory Solid Mechanics,LCD,1,2,2,...,3,3,2,0,0,1,1,0,21,"Ott-Monsivais, Stephanie"
76990,2010,Summer,2010-su,TAM,335,Introductory Fluid Mechanics,LEC,5,8,9,...,0,4,0,0,1,0,2,0,39,"Keane, Richard D"

## Grouping Data in Python  

aggregate groups with .groupby(column name), followed by the aggregation function agg(type), where type can be "count", "sum", "mean", etc  
reset_index() makes the dataframe cleaner

In [2]:
df.groupby("A-").agg("count").reset_index()

,A-,Year,Term,YearTerm,Subject,Number,Course Title,Sched Type,A+,A,...,C+,C,C-,D+,D,D-,F,W,Students,Primary Instructor
0,0,9521,9521,9521,9521,9521,9521,8464,9521,9521,...,9521,9521,9521,9521,9521,9521,9521,9521,9521,9507
1,1,5417,5417,5417,5417,5417,5417,4684,5417,5417,...,5417,5417,5417,5417,5417,5417,5417,5417,5417,5399
2,2,6958,6958,6958,6958,6958,6958,6045,6958,6958,...,6958,6958,6958,6958,6958,6958,6958,6958,6958,6939
3,3,7487,7487,7487,7487,7487,7487,6487,7487,7487,...,7487,7487,7487,7487,7487,7487,7487,7487,7487,7471
4,4,7139,7139,7139,7139,7139,7139,6105,7139,7139,...,7139,7139,7139,7139,7139,7139,7139,7139,7139,7123
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
189,281,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
190,283,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
191,285,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
192,300,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
193,351,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1

In [3]:
df.groupby("Number").agg("count").reset_index()

,Number,Year,Term,YearTerm,Subject,Course Title,Sched Type,A+,A,A-,...,C+,C,C-,D+,D,D-,F,W,Students,Primary Instructor
0,2,7,7,7,7,7,5,7,7,7,...,7,7,7,7,7,7,7,7,7,7
1,12,7,7,7,7,7,7,7,7,7,...,7,7,7,7,7,7,7,7,7,7
2,14,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
3,100,4167,4167,4167,4167,4167,3651,4167,4167,4167,...,4167,4167,4167,4167,4167,4167,4167,4167,4167,4160
4,101,4746,4746,4746,4746,4746,4134,4746,4746,4746,...,4746,4746,4746,4746,4746,4746,4746,4746,4746,4737
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
553,794,33,33,33,33,33,29,33,33,33,...,33,33,33,33,33,33,33,33,33,31
554,795,4,4,4,4,4,4,4,4,4,...,4,4,4,4,4,4,4,4,4,4
555,796,18,18,18,18,18,17,18,18,18,...,18,18,18,18,18,18,18,18,18,18
556,797,16,16,16,16,16,16,16,16,16,...,16,16,16,16,16,16,16,16,16,16
557,798,6,6,6,6,6,5,6,6,6,...,6,6,6,6,6,6,6,6,6,6

using numeric_only=True option avoids adding up strings

In [4]:
df.groupby("Number").agg("sum",numeric_only=True).reset_index()

,Number,Year,A+,A,A-,B+,B,B-,C+,C,C-,D+,D,D-,F,W,Students
0,2,14089,7,11,15,22,15,16,14,21,14,10,9,7,19,13,180
1,12,14087,15,31,45,71,101,92,86,76,55,32,34,30,91,16,759
2,14,4021,1,3,2,5,9,3,2,9,2,3,0,0,4,1,43
3,100,8406184,34288,77054,32017,24082,31613,13117,8447,11781,4514,2533,3415,1529,6915,1015,251305
4,101,9573448,52610,75559,25450,17542,20946,10760,7252,8328,4244,2410,2875,1726,5763,832,235465
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
553,794,66559,31,141,249,447,209,56,8,1,2,1,0,0,1,3,1146
554,795,8075,2,21,24,22,14,8,0,3,0,0,0,0,0,1,94
555,796,36260,29,115,152,179,105,38,7,8,2,0,0,1,0,3,636
556,797,32342,35,83,111,102,81,45,2,2,0,0,0,0,0,0,461
557,798,12083,3,52,65,38,22,8,0,0,0,0,0,0,0,0,188