In [3]:
import random
import pandas as pd

## Simple simulations in Python  

Using Python, collect 13000 obsercations of rolling a 6-sided die:

In [4]:
data = []
for i in range (13000):
    roll = random.randint(1,6)
    d = {"Roll":roll}
    data.append(d)
df = pd.DataFrame(data)
df

       Roll
0         1
1         1
2         5
3         2
4         3
...     ...
12995     2
12996     3
12997     2
12998     1
12999     2

[13000 rows x 1 columns]

Analysis: what is our estimated probability of rolling a number <=4?

In [6]:
df[df["Roll"]<=4].count()/len(df)

Roll    0.670615
dtype: float64

##  Simulations with Conditional  

simulate 100,000 genetic tests to test someone's relation to Taylor Swift. The test has the following parameters:  
1) There is a 99% probability that an individual related to Taylor Swift will get a positive result ("true positive").  
2) There is a 6% probability that an individual NOT related to Taylor Swift will get a positive result ("false positive").  
3) About 1% of the world population is related to Taylor Swift.

In [8]:
data = []
for i in range(100000):
    related = random.randint(1,100)
    test = random.randint(1,100)
    if related == 1:
        if test <= 99:
            result = '+'
        else:
            result = '-'
    else:
        if test <= 6:
            result = '+'
        else:
            result = '-'
    d={"related":related, "test":test, "result":result}
    data.append(d)
df = pd.DataFrame(data)
df

       related  test result
0           96    72      -
1           78     8      -
2           62    50      -
3           29    12      -
4           64    89      -
...        ...   ...    ...
99995       87    49      -
99996       86    68      -
99997        7    94      -
99998       79    32      -
99999       95    92      -

[100000 rows x 3 columns]

## Python functions and simulations

write a function to simulate a single person taking a five-question exam and returns the number of questions they answered correctly

In [ ]:
def takeExam()
    data = []
    for i in range(5):
        score = random.choice([1,0,0,0,0])
        d = {"score":score}
        data.append(d)
        df = pd.DataFrame(data)
        num_correct = len(df[df.score==1])
        return num_correct